### ISSUE TITLE
Actions using Admin credential

### ISSUE THREAD

**Issue by Fen0l** [kakwa/ldapcherry#15]
Hello,

Would like to know if ldapcherry was using the users/admins credentials to perform actions like update/restart password of other users or is it the service account speficied in the config file who perform updates.

If not, does this feature will be available ?

**Comment by kakwa** [comment]
Hello,

Every modifications are done through the "admin account" specified in the configuration file.

It's not possible to do it through the user's account, and I'm not planning to add support for it in future.

Adding this feature would significantly increase the complexity of the code (handling access deny responses from the backend, keeping a connection to the ldap through the user's session, finding the right abstraction (ldapcherry is not limited to ldap)), and it also may increase complexity of deployment.

I'm guessing ldapcherry is not a good feet for you.

Sorry, I hope you will find another solution working for your use case.

have a nice day.
