### ISSUE TITLE
Password encryption/hashing

### ISSUE THREAD

**Issue by wpartyka** [kakwa/ldapcherry#27]
Hello,
what i can see, right now new user has password saved as plaintext, is there possibility to add encryption? (interested mostly in SSHA), or maybe you can pinpoint me where I could implement that :D

**Comment by kakwa** [comment]
My recommendation would be to use the ppolicy overlay (assuming OpenLdap). More specifically the ```olcPPolicyHashCleartext``` attribute of this overlay.

http://www.zytrax.com/books/ldap/ch6/ppolicy.html

However, you are not the first to ask this question, so I'm currently looking on how to implement the hashing on ldapcherry side (using python-passlib). No ETA on that feature however.

Also, as a personal opinion, handling the hashing through the ppolicy overlay is a better choice, that way whatever the application touching the ldap (ldapcherry, phpldapadmin, ldapmodify...), the password is hashed in any case.

**Comment by ConsoleCriminal** [comment]
Is this still in consideration?
While I would prefer ppolicy, the docker container we use for LDAP doesn't have that and I prefer to stick with it than start to mess around with it...
