### ISSUE TITLE
cannot complie...!L215cG9sbzExMS92Zmc=...?

### ISSUE THREAD

**Issue by mypolo111** [kakwa/ldapcherry#58]
looks like lack of library

**Comment by kakwa** [comment]
Could you provide more details? Like a stack trace or environment details (version of python, OS, etc)?

To say the truth, I'm a bit puzzled by the title of this issue: this project is in Python, which is an interpreted language (with a partial just in time "compilation" (.pyc)), it's not like C/CPP with a dedicated compilation phase.
